### PR TITLE
Updated Downloads page

### PR DESCRIPTION
**Pull request by francislewis**
Added link to the source on Github.

### CODE REVIEW

**Comment by ddevault** [comment]
Can you also add a mention that it's available under the terms of the MIT licnese?

**Comment by francislewis** [comment]
Mentioned the MIT license now.

**Comment by ddevault** [comment]
Left a few typos in.

**Comment by francislewis** [comment]
Sorry, corrected now

**Comment by ddevault** [comment]
> KinghtOS

:smile:

**Comment by francislewis** [comment]
Oh, haha. I think I have finally corrected everything now.

**Comment by ddevault** [comment]
Awesome :tada: 

Thanks for the improvement!

**Pull request merged**
