### PR TITLE
Improved KnightOS redesign

### PR DESCRIPTION
**Pull request by altbdoor**
Hi KnightOS team,

After releasing the new design on /g/, a couple of Anons pointed out some weaknesses in the design. I have tried to redesign the site in accordance to the new design, while fixing some problems, for example, mobile views.

At first I thought that Github was able to handle multiple Jekyll sites, but it appears that the [GIthub link](http://altbdoor.github.io/knightos.org/) is broken. However, it appears fine on local testing.

Regards.

### CODE REVIEW

**Comment by ddevault** [comment]
Thanks altbdoor! Can you do me a favor and merge upstream/master into your branch? I can't cleanly apply this patch.

**Comment by altbdoor** [comment]
I suppose you mean upstream/gh-pages. :smile: I just merged the branches, so please test if it works for you.

Also, I forgot to note in the earlier post, that I have to change the toolchain blog post to fit into the new look. Please test it thoroughly, and drop a message if there is anything that needs fixing.

**Comment by ddevault** [comment]
This looks great! Feedback:
- I prefer the source code and mailing lists to be called out in the top-level nav
- Would be better to hide the next/previous buttons on the blog rather than disable them if they aren't useful

Overall I'm very happy. Nice work, thank you!

**Comment by altbdoor** [comment]
> I prefer the source code and mailing lists to be called out in the top-level nav

Hmm, there needs to be a compromise, as the navbar have not much space after all the links and the search bar. What order would you suggest? What should be dropdown and not?

Edit: Generally, everything in navbar should fit on tablet view (768px in width).

> Would be better to hide the next/previous buttons on the blog rather than disable them if they aren't useful

Working on it!

**Comment by ddevault** [comment]
> Hmm, there needs to be a compromise, as the navbar have not much space after all the links and the search bar. What order would you suggest? What should be dropdown and not?

How about making the drop-down named "Source Code"? Then you get both the code and things related to the code when you click it.

**Comment by altbdoor** [comment]
> How about making the drop-down named "Source Code"? Then you get both the code and things related to the code when you click it.

That would fit the description for Github and Contributing link, but not really accurate for Mailing Lists and IRC Chat.

capture

**Comment by ddevault** [comment]
No one reads the docs on their phones (hardly anyone leaves the home page on their phones).

**Comment by altbdoor** [comment]
> No one reads the docs on their phones (hardly anyone leaves the home page on their phones).

Haha, I see. If we were to make that assumption, would the image below be fitting? Or should I change the order of items?

capture

**Comment by ddevault** [comment]
Can you put mailing list and irc chat under the source code dropdown as well? It's kind of lonely without them. Also, GitHub refers to be called "GitHub".

**Comment by altbdoor** [comment]
> Can you put mailing list and irc chat under the source code dropdown as well? It's kind of lonely without them. Also, GitHub refers to be called "GitHub".

All done, please check the latest commit :wink:

**Comment by ddevault** [comment]
This is beautiful. Thank you :heart:

**Comment by altbdoor** [comment]
Glad to help! You're most welcomed.

**Pull request merged**
