### PR TITLE
Added CSS for container div

### PR DESCRIPTION
**Pull request by francislewis**
This will make the SDK page look a bit better

### CODE REVIEW

**Comment by ddevault** [comment]
This doesn't appear to improve the SDK page in any way I can notice.

**Comment by ddevault** [comment]
What needs to happen to fix the SDK page is that it should be wrapped in a container.

**Comment by ddevault** [comment]
And adding a margin to all containers make every _other_ page look words :frowning:

**Comment by francislewis** [comment]
My bad, changed it to margin-left so the text isn't stuck to the side of the screen

**Comment by francislewis** [comment]
Should I try a page specific div?

**Comment by ddevault** [comment]
Yeah, in sdk.html just wrap the content in a `div.container`.

**Comment by francislewis** [comment]
Sorry for being a bit of a noob, but I'm not sure what you mean by that?

**Comment by ddevault** [comment]
Correct: https://github.com/KnightOS/knightos.org/blob/gh-pages/_layouts/post.html#L8

Incorrect: https://github.com/KnightOS/knightos.org/blob/gh-pages/sdk.html#L6

The content of the page needs to be wrapped in a container div.

**Comment by francislewis** [comment]
Would it be better to wrap it as .sdk-container as to not mess up other pages or keep it as just .container?

**Comment by ddevault** [comment]
Ditch the CSS changes (which _did_ mess up the other pages) and just add a container div to sdk.html. That's all that needs to happen.

**Comment by francislewis** [comment]
Done, this pull request is now useless.

**Comment by ddevault** [comment]
Do you want to make a new one for the sdk.html changes?

**Comment by francislewis** [comment]
https://github.com/KnightOS/knightos.org/pull/17 - should be there

**Pull request closed without merging**
